#pragma once

inline void loadMenukeyConfig(const std::string& configPath)
{
	std::ifstream configFile(configPath);

	nlohmann::json j;
	configFile >> j;


	if (j.contains("CBot Menu KeyButton") && j["CBot Menu KeyButton"].is_number()) gui::m_selectedKey = j["CBot Menu KeyButton"].get<int>();

	configFile.close();
}

inline void saveMenukeyConfig(const std::string& configPath)
{
	nlohmann::json j;
	j["CBot Menu KeyButton"] = gui::m_selectedKey;

	std::ofstream configFile(configPath);
	configFile << j.dump(4);

	configFile.close();
}

inline void writeTutorialKeys()
{
    std::ofstream outFile("KeyCodes.txt");

    outFile <<
        "    KEY_Unknown = -1,\n"
        "    KEY_None = 0,\n"
        "    KEY_Backspace = 8,\n"
        "    KEY_Tab = 9,\n"
        "    KEY_Clear = 12,\n"
        "    KEY_Enter = 13,\n"
        "    KEY_Shift = 16,\n"
        "    KEY_Control = 17,\n"
        "    KEY_Alt = 18,\n"
        "    KEY_Pause = 19,\n"
        "    KEY_CapsLock = 20,\n"
        "    KEY_Escape = 27,\n"
        "    KEY_Space = 32,\n"
        "    KEY_PageUp = 33,\n"
        "    KEY_PageDown = 34,\n"
        "    KEY_End = 35,\n"
        "    KEY_Home = 36,\n"
        "    KEY_Left = 37,\n"
        "    KEY_Up = 38,\n"
        "    KEY_Right = 39,\n"
        "    KEY_Down = 40,\n"
        "    KEY_Select = 41,\n"
        "    KEY_Print = 42,\n"
        "    KEY_Execute = 43,\n"
        "    KEY_PrintScreen = 44,\n"
        "    KEY_Insert = 45,\n"
        "    KEY_Delete = 46,\n"
        "    KEY_Help = 47,\n"
        "    KEY_Zero = 48,\n"
        "    KEY_One = 49,\n"
        "    KEY_Two = 50,\n"
        "    KEY_Three = 51,\n"
        "    KEY_Four = 52,\n"
        "    KEY_Five = 53,\n"
        "    KEY_Six = 54,\n"
        "    KEY_Seven = 55,\n"
        "    KEY_Eight = 56,\n"
        "    KEY_Nine = 57,\n"
        "    KEY_A = 65,\n"
        "    KEY_B = 66,\n"
        "    KEY_C = 67,\n"
        "    KEY_D = 68,\n"
        "    KEY_E = 69,\n"
        "    KEY_F = 70,\n"
        "    KEY_G = 71,\n"
        "    KEY_H = 72,\n"
        "    KEY_I = 73,\n"
        "    KEY_J = 74,\n"
        "    KEY_K = 75,\n"
        "    KEY_L = 76,\n"
        "    KEY_M = 77,\n"
        "    KEY_N = 78,\n"
        "    KEY_O = 79,\n"
        "    KEY_P = 80,\n"
        "    KEY_Q = 81,\n"
        "    KEY_R = 82,\n"
        "    KEY_S = 83,\n"
        "    KEY_T = 84,\n"
        "    KEY_U = 85,\n"
        "    KEY_V = 86,\n"
        "    KEY_W = 87,\n"
        "    KEY_X = 88,\n"
        "    KEY_Y = 89,\n"
        "    KEY_Z = 90,\n"
        "    KEY_LeftWindowsKey = 91,\n"
        "    KEY_RightWindowsKey = 92,\n"
        "    KEY_ApplicationsKey = 93,\n"
        "    KEY_Sleep = 95,\n"
        "    KEY_NumPad0 = 96,\n"
        "    KEY_NumPad1 = 97,\n"
        "    KEY_NumPad2 = 98,\n"
        "    KEY_NumPad3 = 99,\n"
        "    KEY_NumPad4 = 100,\n"
        "    KEY_NumPad5 = 101,\n"
        "    KEY_NumPad6 = 102,\n"
        "    KEY_NumPad7 = 103,\n"
        "    KEY_NumPad8 = 104,\n"
        "    KEY_NumPad9 = 105,\n"
        "    KEY_Multiply = 106,\n"
        "    KEY_Add = 107,\n"
        "    KEY_Seperator = 108,\n"
        "    KEY_Subtract = 109,\n"
        "    KEY_Decimal = 110,\n"
        "    KEY_Divide = 111,\n"
        "    KEY_F1 = 112,\n"
        "    KEY_F2 = 113,\n"
        "    KEY_F3 = 114,\n"
        "    KEY_F4 = 115,\n"
        "    KEY_F5 = 116,\n"
        "    KEY_F6 = 117,\n"
        "    KEY_F7 = 118,\n"
        "    KEY_F8 = 119,\n"
        "    KEY_F9 = 120,\n"
        "    KEY_F10 = 121,\n"
        "    KEY_F11 = 122,\n"
        "    KEY_F12 = 123,\n"
        "    KEY_F13 = 124,\n"
        "    KEY_F14 = 125,\n"
        "    KEY_F15 = 126,\n"
        "    KEY_F16 = 127,\n"
        "    KEY_F17 = 128,\n"
        "    KEY_F18 = 129,\n"
        "    KEY_F19 = 130,\n"
        "    KEY_F20 = 131,\n"
        "    KEY_F21 = 132,\n"
        "    KEY_F22 = 133,\n"
        "    KEY_F23 = 134,\n"
        "    KEY_F24 = 135,\n"
        "    KEY_Numlock = 144,\n"
        "    KEY_ScrollLock = 145,\n"
        "    KEY_LeftShift = 160,\n"
        "    KEY_RightShift = 161,\n"
        "    KEY_LeftControl = 162,\n"
        "    KEY_RightContol = 163,\n"
        "    KEY_LeftMenu = 164,\n"
        "    KEY_RightMenu = 165,\n"
        "    KEY_BrowserBack = 166,\n"
        "    KEY_BrowserForward = 167,\n"
        "    KEY_BrowserRefresh = 168,\n"
        "    KEY_BrowserStop = 169,\n"
        "    KEY_BrowserSearch = 170,\n"
        "    KEY_BrowserFavorites = 171,\n"
        "    KEY_BrowserHome = 172,\n"
        "    KEY_VolumeMute = 173,\n"
        "    KEY_VolumeDown = 174,\n"
        "    KEY_VolumeUp = 175,\n"
        "    KEY_NextTrack = 176,\n"
        "    KEY_PreviousTrack = 177,\n"
        "    KEY_StopMedia = 178,\n"
        "    KEY_PlayPause = 179,\n"
        "    KEY_LaunchMail = 180,\n"
        "    KEY_SelectMedia = 181,\n"
        "    KEY_LaunchApp1 = 182,\n"
        "    KEY_LaunchApp2 = 183,\n"
        "    KEY_OEM1 = 186,\n"
        "    KEY_OEMPlus = 184,\n"
        "    KEY_OEMComma = 188,\n"
        "    KEY_OEMMinus = 189,\n"
        "    KEY_OEMPeriod = 190,\n"
        "    KEY_OEM2 = 191,\n"
        "    KEY_OEM3 = 192,\n"
        "    KEY_OEM4 = 219,\n"
        "    KEY_OEM5 = 220,\n"
        "    KEY_OEM6 = 221,\n"
        "    KEY_OEM7 = 222,\n"
        "    KEY_OEM8 = 223,\n"
        "    KEY_OEM102 = 226,\n"
        "    KEY_Process = 229,\n"
        "    KEY_Packet = 231,\n"
        "    KEY_Attn = 246,\n"
        "    KEY_CrSel = 247,\n"
        "    KEY_ExSel = 248,\n"
        "    KEY_EraseEOF = 249,\n"
        "    KEY_Play = 250,\n"
        "    KEY_Zoom = 251,\n"
        "    KEY_PA1 = 253,\n"
        "    KEY_OEMClear = 254,\n"
        "    KEY_ArrowUp = 283,\n"
        "    KEY_ArrowDown = 284,\n"
        "    KEY_ArrowLeft = 285,\n"
        "    KEY_ArrowRight = 286,\n"
        "    CONTROLLER_A = 1001,\n"
        "    CONTROLLER_B = 1003,\n"
        "    CONTROLLER_Y = 1005,\n"
        "    CONTROLLER_X = 1007,\n"
        "    CONTROLLER_Start = 1009,\n"
        "    CONTROLLER_Back = 1011,\n"
        "    CONTROLLER_RB = 1013,\n"
        "    CONTROLLER_LB = 1015,\n"
        "    CONTROLLER_RT = 1017,\n"
        "    CONTROLLER_LT = 1019,\n"
        "    CONTROLLER_Up = 1021,\n"
        "    CONTROLLER_Down = 1023,\n"
        "    CONTROLLER_Left = 1025,\n"
        "    CONTROLLER_Right = 1027,\n"
        "    CONTROLLER_LTHUMBSTICK_UP = 1029,\n"
        "    CONTROLLER_LTHUMBSTICK_DOWN = 1031,\n"
        "    CONTROLLER_LTHUMBSTICK_LEFT = 1033,\n"
        "    CONTROLLER_LTHUMBSTICK_RIGHT = 1035,\n"
        "    CONTROLLER_RTHUMBSTICK_UP = 1037,\n"
        "    CONTROLLER_RTHUMBSTICK_DOWN = 1039,\n"
        "    CONTROLLER_RTHUMBSTICK_LEFT = 1041,\n"
        "    CONTROLLER_RTHUMBSTICK_RIGHT = 1043,\n"
        "    // Geode additions\n"
        "    KEY_GraveAccent = 4096,\n"
        "    KEY_OEMEqual = 4097,\n"
        "    KEY_LeftBracket = 4098,\n"
        "    KEY_RightBracket = 4099,\n"
        "    KEY_Backslash = 4100,\n"
        "    KEY_Semicolon = 4101,\n"
        "    KEY_Apostrophe = 4102,\n"
        "    KEY_Slash = 4103,\n"
        "    KEY_Equal = 4104,\n"
        "    KEY_NumEnter = 4105,\n"
        "    KEY_World1 = 4106,\n"
        "    KEY_World2 = 4107,\n"
        "    MOUSE_4 = 4352,\n"
        "    MOUSE_5 = 4353,\n"
        "    MOUSE_6 = 4354,\n"
        "    MOUSE_7 = 4355,\n"
        "    MOUSE_8 = 4356";

    outFile.close();
}